Repository mnurzyns/ParkSpaceSharing, pull requests merged in 2023-05, with the labels that each got.

#54 fix wrong behavior of some PATCH endpoints
  server/src/controller/OfferController.hh
  server/src/controller/PlaceController.hh
  server/src/service/OfferService.cc
  server/src/service/OfferService.hh
  server/src/service/PlaceService.cc
  server/src/service/UserService.cc
  server/src/service/UserService.hh
Labels: bug, critical

#62 add telephone number field to User
  server/CMakeLists.txt
  server/migrations/001_init.sql
  server/migrations/002_sample_data.sql
  server/src/EmailValidation.cc
  server/src/Validator.cc
  server/src/Validator.hh
  server/src/component/SwaggerComponent.hh
  server/src/controller/OfferController.hh
  server/src/controller/PlaceController.hh
  server/src/controller/UserController.hh
  server/src/database/MainDatabase.cc
  server/src/database/MainDatabase.hh
  server/src/dto/AuthDto.hh
  server/src/dto/SignUpDto.hh
  server/src/dto/UserDto.hh
  server/src/service/AuthService.cc
  server/src/service/PlaceService.hh
  server/src/service/UserService.cc
Labels: enhancement

#66 return HTTP status 201 instead of 200 in POST and PUT endpoints
  server/src/controller/OfferController.hh
  server/src/controller/PlaceController.hh
  server/src/controller/UserController.hh
  server/src/service/UserService.cc
Labels: invalid

#63 improve offer searching
  server/src/controller/OfferController.hh
  server/src/controller/PlaceController.hh
  server/src/dto/OfferDto.hh
  server/src/dto/PlaceDto.hh
  server/src/service/OfferService.cc
  server/src/service/OfferService.hh
  server/src/service/PlaceService.cc
  server/src/service/PlaceService.hh
Labels: enhancement

#75 refactor FTS tables structure
  server/migrations/001_init.sql
  server/migrations/002_sample_data.sql
  server/src/dto/OfferDto.hh
  server/src/dto/PlaceDto.hh
  server/src/service/OfferService.cc
  server/src/service/PlaceService.cc
  server/src/service/UserService.cc
Labels: enhancement, invalid
